// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeDirectory(arg1:main.Directory,arg2:boolean):Promise<main.Directory>;

export function Greet(arg1:string):Promise<string>;

export function NewDirectory():Promise<main.Directory>;

export function NewFile():Promise<main.File>;
