// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDirectory(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeDirectory'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NewDirectory() {
  return window['go']['main']['App']['NewDirectory']();
}

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}
